#spring.application.name=extract

server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BigHwangTaeYeon/mungmo_config
