#spring.application.name=boardService

server:
  port: 0
  servlet:
    context-path: /board-service

spring:
  application:
    name: board-application
  config:
    import:
      - classpath:/yml/file.yml
  cloud:
    config:
      uri: http://127.0.0.1:8888 #config 서버가 돌아가는 주소
      name: board-application #repo에 있는 파일이름
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
  instance-id: ${spring.cloud.client.hostname}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
